### ISSUE TITLE
Why not ES5?

### ISSUE THREAD

**Issue by brettstimmerman** [olivierlesnicki/flight-withEach#1]
Hi Olivier,

NIce to see another Flight component author! I found `withEach` from browsing http://flight-components.jit.su/. After poking briefly at the README, I wondered:

Is there a reason that, at a quick glance I don't understand how this is better than using ES5 Array and Object methods and [es5-shim](https://github.com/kriskowal/es5-shim/), which Flight depends on? Have I missed something crucial?

Mostly, I'm concerned that mixing functionality into components that could otherwise be solved at the language level (or shim) is not the best solution.

I realize there is no `Object.each` in ES5, which is a shame. But it can also be shimmed or manually hammered out with `Object.keys` or `for...in` shenanigans without requiring a mixin.

**Comment by olivierlesnicki** [comment]
I think the reason why you don't understand how this is better than using methods made available by es5-shim is because it's not. I've never actually looked at the new Array and Object methods the library was exposing: I guess I have a bit of homework to do.

Many thanks for your comment!

**Comment by olivierlesnicki** [comment]
Although thinking about it the mixin does use ES5 under the hood

``` javascript
if (Array.prototype.forEach && obj.forEach === Array.prototype.forEach) {
  obj.forEach(iterator, context);
}
```

But I get your point, because flight depends on es5-shim these methods will always be available therefore the requirement for a component is useless.

**Comment by brettstimmerman** [comment]
Exactly. It can be solved without a component/mixin. The one missing piece then is parity with `each({one: 1, ...})`, which can be shimmed in a similar way if needed.
